const express = require('express');
const { requireUserId } = require('../middlewares/auth.middleware');
const { listLive, startLive, endLive, joinLive, getLiveToken } = require('../controllers/live.controller');
const router = express.Router();
router.get('/', requireUserId, listLive);
router.post('/', requireUserId, startLive);
router.post('/:id/join', requireUserId, joinLive);
router.get('/:id/token', requireUserId, getLiveToken);
router.post('/:id/end', requireUserId, endLive);
module.exports = router;
