import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Bookmark, Compass, Heart, Library, MessageCircle, MoreHorizontal, Pause, Play, Radio, Send, Settings, Trash2, UserRound, Volume2, VolumeX } from 'lucide-react';
import { Link as RouterLink } from 'react-router-dom';
import { motion } from 'framer-motion';
import StarlightLogo from '../components/StarlightLogo';
import { defaultGradient, gradientFor } from '../utils/gradients';
import ChatInbox from '../components/ChatInbox';

const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:4000';
const Link = (props) => <RouterLink {...props} to={props.children === 'Settings' ? '/settings' : props.to} />;
const dateLabel = (value) => value ? new Date(value).toLocaleDateString([], { month: 'short', day: 'numeric' }) : '';

function FeedCard({ item, user, onUpdate, onDelete }) {
  const cardRef = useRef(null); const audioRef = useRef(null);
  const [playing, setPlaying] = useState(false); const [muted, setMuted] = useState(true); const [comment, setComment] = useState(''); const [replyTo, setReplyTo] = useState(null); const [showComments, setShowComments] = useState(false); const [menuOpen, setMenuOpen] = useState(false);
  const stop = () => { audioRef.current?.pause(); setPlaying(false); };
  const play = async () => { if (!audioRef.current) return; try { await audioRef.current.play(); setPlaying(true); } catch { setPlaying(false); } };
  useEffect(() => {
    const audio = new Audio(item.url); audio.preload = 'metadata'; audio.muted = true; audioRef.current = audio;
    const start = Number(item.previewStart || 0); const end = item.previewEnd == null ? null : Number(item.previewEnd);
    const seek = () => { if (start > 0) audio.currentTime = start; }; const finish = () => { audio.currentTime = start; setPlaying(false); };
    audio.addEventListener('loadedmetadata', seek); audio.addEventListener('ended', finish); audio.addEventListener('timeupdate', () => { if (end && audio.currentTime >= end) finish(); });
    const observer = new IntersectionObserver(([entry]) => entry.isIntersecting && entry.intersectionRatio >= 0.65 ? play() : stop(), { threshold: [0, 0.65, 1] });
    if (cardRef.current) observer.observe(cardRef.current); return () => { observer.disconnect(); audio.pause(); audio.src = ''; };
  }, [item.id, item.url, item.previewStart, item.previewEnd]);
  const toggleMute = () => { const next = !muted; setMuted(next); if (audioRef.current) audioRef.current.muted = next; };
  const toggleLike = async () => { const next = !item.likedByMe; onUpdate(item.id, { likedByMe: next, likeCount: Math.max(0, (item.likeCount || 0) + (next ? 1 : -1)) }, 'like'); const res = await fetch(`${apiUrl}/api/feed/tracks/${item.id}/like`, { method: 'POST' }); if (!res.ok) onUpdate(item.id, { likedByMe: !next, likeCount: item.likeCount || 0 }, 'like'); };
  const toggleSave = async () => { const next = !item.savedByMe; onUpdate(item.id, { savedByMe: next }, 'save'); const res = await fetch(`${apiUrl}/api/feed/tracks/${item.id}/save`, { method: 'POST' }); if (!res.ok) onUpdate(item.id, { savedByMe: !next }, 'save'); };
  const commentAction = async (event) => { event.preventDefault(); if (!comment.trim()) return; const res = await fetch(`${apiUrl}/api/feed/tracks/${item.id}/comments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: comment, parentId: replyTo?.id }) }); if (res.ok) { const data = await res.json(); onUpdate(item.id, data.comment, 'comment'); setComment(''); setReplyTo(null); setShowComments(true); } };
  const reactComment = async (entry) => { const next = !entry.likedByMe; onUpdate(item.id, { ...entry, likedByMe: next, likeCount: Math.max(0, (entry.likeCount || 0) + (next ? 1 : -1)) }, 'comment-like'); const res = await fetch(`${apiUrl}/api/feed/tracks/${item.id}/comments/${entry.id}/like`, { method: 'POST' }); if (!res.ok) onUpdate(item.id, { ...entry, likedByMe: !next, likeCount: entry.likeCount || 0 }, 'comment-like'); };
  const roots = (item.comments || []).filter((entry) => !entry.parentId); const replies = (id) => (item.comments || []).filter((entry) => entry.parentId === id);
  return <motion.article ref={cardRef} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="relative mx-auto w-full max-w-xl overflow-hidden rounded-2xl border border-border bg-shading/35">
    <Link to={'/profile/' + item.owner?.id} className="absolute left-0 top-0 z-10 h-14 w-3/4" aria-label={'Open ' + (item.owner?.name || 'artist') + ' profile'} />
    <div className="flex items-center gap-3 px-4 py-3">{item.owner?.avatarUrl ? <img src={item.owner.avatarUrl} alt="" className="h-8 w-8 rounded-full object-cover" /> : <div className="grid h-8 w-8 place-items-center rounded-full bg-highlight text-sm font-semibold">{(item.owner?.name || user?.name || '?').slice(0, 1).toUpperCase()}</div>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.owner?.name || 'Unknown artist'}</p><p className="text-xs text-secondary-label">{dateLabel(item.publishedAt || item.uploadedAt)}</p></div>{item.owner?.id === user?.id && <div className="relative"><button onClick={() => setMenuOpen((value) => !value)} className="grid h-8 w-8 place-items-center rounded-full hover:bg-highlight" aria-label="Feed options"><MoreHorizontal className="h-5 w-5" /></button>{menuOpen && <div className="absolute right-0 top-9 z-10 w-44 rounded-xl border border-border bg-primary-background p-1 shadow-2xl"><button onClick={() => { setMenuOpen(false); onDelete(item.id); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm text-red-400 hover:bg-red-500/10"><Trash2 className="h-4 w-4" />Delete preview</button></div>}</div>}</div>
    <div className="relative aspect-square w-full overflow-hidden bg-black sm:aspect-[4/3]">{item.project?.coverArt ? <img src={item.project.coverArt} alt="" className="block h-full w-full object-cover" /> : <div className={`h-full w-full bg-gradient-to-br ${gradientFor(item.id) || defaultGradient}`} />}<button onClick={() => playing ? stop() : play()} className="absolute inset-0 m-auto grid h-12 w-12 place-items-center rounded-full bg-primary-label text-primary-background shadow-xl hover:scale-105" aria-label={playing ? 'Pause preview' : 'Play preview'}>{playing ? <Pause className="h-4 w-4 fill-current" /> : <Play className="ml-1 h-4 w-4 fill-current" />}</button><button onClick={toggleMute} className="absolute bottom-3 right-3 grid h-9 w-9 place-items-center rounded-full bg-black/65 text-white hover:bg-black/85" aria-label={muted ? 'Unmute preview' : 'Mute preview'}>{muted ? <VolumeX className="h-4 w-4" /> : <Volume2 className="h-4 w-4" />}</button><span className="absolute bottom-3 left-3 rounded-full bg-black/65 px-2.5 py-1 text-[11px] font-semibold text-white">{playing ? 'Previewing' : 'Preview'}</span></div>
    <div className="px-4 py-3"><h2 className="font-semibold">{item.title || 'Untitled track'}</h2><p className="mt-1 text-sm text-secondary-label">{item.project?.title || 'Project preview'}</p>{item.feedCaption && <p className="mt-2 text-sm">{item.feedCaption}</p>}<div className="mt-3 flex items-center gap-4"><button onClick={toggleLike} className={`inline-flex items-center gap-1.5 text-sm ${item.likedByMe ? 'text-red-400' : 'text-secondary-label hover:text-primary-label'}`} aria-label="Like preview"><Heart className={`h-5 w-5 ${item.likedByMe ? 'fill-current' : ''}`} />{item.likeCount || 0}</button><button onClick={() => setShowComments((value) => !value)} className="inline-flex items-center gap-1.5 text-sm text-secondary-label hover:text-primary-label" aria-label="Show comments"><MessageCircle className="h-5 w-5" />{item.comments?.length || 0}</button></div>{showComments && <div className="mt-3 border-t border-border pt-3"><div className="max-h-48 space-y-3 overflow-y-auto">{roots.map((entry) => <div key={entry.id} className="text-sm"><div className="flex gap-2"><span className="font-semibold">{entry.user?.name || 'User'}</span><span className="min-w-0 flex-1 break-words text-secondary-label">{entry.text}</span></div><div className="mt-1 flex items-center gap-3 pl-1 text-xs text-secondary-label"><button onClick={() => reactComment(entry)} className={entry.likedByMe ? 'text-red-400' : ''}><Heart className={`mr-1 inline h-3.5 w-3.5 ${entry.likedByMe ? 'fill-current' : ''}`} />{entry.likeCount || 0}</button><button onClick={() => { setReplyTo(entry); setComment(`@${entry.user?.name || 'user'} `); }}>Reply</button></div>{replies(entry.id).map((reply) => <div key={reply.id} className="ml-5 mt-2 flex gap-2 border-l border-border pl-3"><span className="font-semibold">{reply.user?.name || 'User'}</span><span className="break-words text-secondary-label">{reply.text}</span></div>)}</div>)}</div><form onSubmit={commentAction} className="mt-3 flex items-center gap-2">{replyTo && <button type="button" onClick={() => { setReplyTo(null); setComment(''); }} className="text-xs text-secondary-label">Cancel reply</button>}<input value={comment} onChange={(event) => setComment(event.target.value)} maxLength={500} placeholder={replyTo ? `Reply to ${replyTo.user?.name || 'user'}...` : 'Add a comment...'} className="min-w-0 flex-1 rounded-full border border-border bg-shading px-3 py-2 text-sm outline-none" /><button className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-primary-label text-primary-background" aria-label="Post comment"><Send className="h-4 w-4" /></button></form></div>}</div>
  </motion.article>;
}

export default function Feed({ user, savedOnly = false }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [inboxOpen, setInboxOpen] = useState(false);
  useEffect(() => { fetch(`${apiUrl}/api/feed`).then(async (res) => { const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Could not load feed.'); setItems(data.items || []); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  const updateItem = (id, value, type) => setItems((current) => current.map((item) => { if (item.id !== id) return item; if (type === 'like') return { ...item, ...value }; if (type === 'comment-like') return { ...item, comments: (item.comments || []).map((entry) => entry.id === value.id ? value : entry) }; return { ...item, comments: [...(item.comments || []), value] }; }));
  const deleteItem = async (id) => { if (!window.confirm('Delete this feed preview?')) return; const res = await fetch(`${apiUrl}/api/feed/tracks/${id}`, { method: 'DELETE' }); if (res.ok) setItems((current) => current.filter((item) => item.id !== id)); };
  const navItems = [{ label: 'Profile', icon: UserRound, to: '/profile/' + user.id }, { label: 'Saved', icon: Bookmark, to: '/saved' }, { label: 'Library', icon: Library, to: '/library' }];
  return <div className="min-h-screen bg-primary-background text-primary-label"><aside className="fixed inset-y-0 left-0 z-30 hidden w-56 border-r border-border/60 bg-primary-background px-4 py-6 lg:flex lg:flex-col"><Link to="/feed" className="mb-10 px-3"><StarlightLogo className="logo-glow h-10 w-40 text-primary-label" /></Link><nav className="space-y-1">{navItems.map(({ label, icon: Icon, to }) => <Link key={label} to={to} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-secondary-label transition-colors hover:bg-highlight hover:text-primary-label"><Icon className="h-5 w-5" />{label}</Link>)}<button onClick={() => setInboxOpen(true)} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold text-secondary-label transition-colors hover:bg-highlight hover:text-primary-label"><MessageCircle className="h-5 w-5" />Inbox</button><Link to={'/profile/' + user.id} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-secondary-label transition-colors hover:bg-highlight hover:text-primary-label"><Settings className="h-5 w-5" />Settings</Link></nav><div className="mt-auto rounded-xl border border-border bg-shading/40 p-3 text-xs text-secondary-label">Share previews, discover new work, and stay connected.</div></aside><header className="sticky top-0 z-20 flex items-center justify-between border-b border-border/60 bg-primary-background/95 px-4 py-4 backdrop-blur lg:ml-56 lg:hidden"><Link to="/library" className="grid h-9 w-9 place-items-center rounded-full bg-shading hover:bg-highlight" aria-label="Back to library"><ArrowLeft className="h-4 w-4" /></Link><StarlightLogo className="logo-glow h-8 w-32 text-primary-label" /><button onClick={() => setInboxOpen(true)} className="grid h-9 w-9 place-items-center rounded-full bg-shading hover:bg-highlight" aria-label="Open inbox"><MessageCircle className="h-4 w-4" /></button></header><main className="px-4 pb-20 sm:px-8 lg:ml-56"><div className="mx-auto max-w-2xl py-7"><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-secondary-label">Discover</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Feed</h1><p className="mt-2 text-sm text-secondary-label">Preview new music from the Rare Motion community.</p></div>{loading && <p className="py-16 text-center text-sm text-secondary-label">Loading previews...</p>}{error && <p className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">{error}</p>}<div className="space-y-6">{items.map((item) => <FeedCard key={item.id} item={item} user={user} onUpdate={updateItem} onDelete={deleteItem} />)}</div></div></main><ChatInbox user={user} isOpen={inboxOpen} onToggle={() => setInboxOpen((value) => !value)} /></div>;
}
