import { useEffect, useState } from 'react';
import { ArrowLeft, Check, Play, UserPlus } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import StarlightLogo from '../components/StarlightLogo';

const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:4000';

export default function Profile({ user }) {
  const { id } = useParams();
  const [profile, setProfile] = useState(null);
  const [posts, setPosts] = useState([]);
  const [following, setFollowing] = useState(false);
  useEffect(() => { fetch(`${apiUrl}/api/auth/${id}`).then((res) => res.json()).then((data) => { setProfile(data.user); setPosts(data.posts || []); setFollowing(Boolean(data.isFollowing)); }); }, [id]);
  const toggleFollow = async () => { const next = !following; setFollowing(next); setProfile((current) => ({ ...current, followerCount: Math.max(0, (current.followerCount || 0) + (next ? 1 : -1)) })); const res = await fetch(`${apiUrl}/api/auth/${id}/follow`, { method: 'POST' }); if (!res.ok) setFollowing(!next); };
  if (!profile) return <div className="min-h-screen bg-primary-background p-8 text-secondary-label">Loading profile...</div>;
  return <div className="min-h-screen bg-primary-background px-5 pb-20 text-primary-label sm:px-8"><header className="mx-auto flex max-w-3xl items-center justify-between border-b border-border/60 py-4"><Link to="/feed" className="grid h-10 w-10 place-items-center rounded-full bg-shading hover:bg-highlight" aria-label="Back"><ArrowLeft className="h-5 w-5" /></Link><StarlightLogo className="logo-glow h-9 w-36 text-primary-label" /><span className="w-10" /></header><main className="mx-auto max-w-3xl py-10"><section className="flex flex-col items-center text-center sm:flex-row sm:items-start sm:gap-8 sm:text-left">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="" className="h-28 w-28 rounded-full object-cover ring-2 ring-border" /> : <div className="grid h-28 w-28 place-items-center rounded-full bg-highlight text-4xl font-semibold">{profile.name?.slice(0, 1).toUpperCase()}</div>}<div className="mt-5 min-w-0 flex-1 sm:mt-1"><div className="flex flex-col items-center gap-3 sm:flex-row"><div><h1 className="text-2xl font-semibold">{profile.name}</h1><p className="text-sm text-secondary-label">@{profile.username || profile.name}</p></div>{profile.id !== user?.id && <button onClick={toggleFollow} className={`inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm font-semibold ${following ? 'bg-shading' : 'bg-primary-label text-primary-background'}`}>{following ? <Check className="h-4 w-4" /> : <UserPlus className="h-4 w-4" />}{following ? 'Following' : 'Follow'}</button>}</div><p className="mt-4 max-w-md text-sm text-secondary-label">{profile.bio || 'Music maker and creative.'}</p><div className="mt-5 flex justify-center gap-7 text-sm sm:justify-start"><span><strong>{posts.length}</strong> posts</span><span><strong>{profile.followerCount || 0}</strong> followers</span><span><strong>{profile.followingCount || 0}</strong> following</span></div></div></section><div className="mt-12 border-t border-border pt-6"><h2 className="mb-5 text-sm font-semibold uppercase tracking-[0.18em] text-secondary-label">Posts</h2>{posts.length === 0 ? <p className="py-12 text-center text-sm text-secondary-label">No published previews yet.</p> : <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{posts.map((post) => <Link key={post.id} to={`/project/${post.projectId}`} className="group relative aspect-square overflow-hidden rounded-xl bg-highlight"><div className="absolute inset-0 grid place-items-center bg-black/20 transition-colors group-hover:bg-black/45"><Play className="h-8 w-8 fill-white text-white opacity-0 transition-opacity group-hover:opacity-100" /></div><div className="absolute bottom-2 left-2 right-2 truncate text-xs font-semibold text-white">{post.title}</div></Link>)}</div>}</div></main></div>;
}
