import { useEffect, useState } from 'react';
import { ArrowLeft, Bookmark, Play, Music2 } from 'lucide-react';
import { Link } from 'react-router-dom';
const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:4000';
export default function Saved() {
  const [items, setItems] = useState([]); const [beats, setBeats] = useState([]);
  useEffect(() => { Promise.all([fetch(apiUrl + '/api/feed', { credentials: 'include' }).then((res) => res.json()), fetch(apiUrl + '/api/marketplace/saved', { credentials: 'include' }).then((res) => res.ok ? res.json() : { beats: [] })]).then(([feed, marketplace]) => { setItems((feed.items || []).filter((item) => item.savedByMe)); setBeats(marketplace.beats || []); }).catch(() => {}); }, []);
  return <div className="min-h-screen bg-primary-background px-4 pb-20 text-primary-label sm:px-8"><header className="mx-auto flex max-w-4xl items-center justify-between py-4"><Link to="/feed" className="grid h-10 w-10 place-items-center rounded-xl bg-shading hover:bg-highlight" aria-label="Back to feed"><ArrowLeft className="h-5 w-5" /></Link><h1 className="font-display text-base font-bold tracking-wider">sAvEd</h1><Bookmark className="h-5 w-5 text-secondary-label" /></header><main className="mx-auto max-w-4xl py-8"><h1 className="font-display text-3xl font-bold tracking-wider">sAvEd</h1><section className="mt-8"><h2 className="text-lg font-bold">Saved previews</h2>{items.length === 0 ? <p className="py-8 text-sm text-secondary-label">No saved previews yet.</p> : <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{items.map((item) => <Link key={item.id} to="/feed" className="group relative aspect-square overflow-hidden rounded-xl bg-highlight">{item.project?.coverArt && <img src={item.project.coverArt} alt="" className="h-full w-full object-cover" />}<div className="absolute inset-0 grid place-items-center bg-black/20 group-hover:bg-black/45"><Play className="h-8 w-8 fill-white text-[#34483B] opacity-0 group-hover:opacity-100" /></div><span className="absolute bottom-2 left-2 right-2 truncate text-xs font-semibold text-[#34483B]">{item.title}</span></Link>)}</div>}</section><section className="mt-10"><h2 className="text-lg font-bold">Saved beats</h2>{beats.length === 0 ? <p className="py-8 text-sm text-secondary-label">No saved beats yet.</p> : <div className="mt-4 grid gap-4 sm:grid-cols-2">{beats.map((beat) => <article key={beat.id} className="rounded-2xl bg-[#34483B] p-4 text-[#F4EBDD]"><div className="flex items-center gap-2"><Music2 className="h-5 w-5" /><div className="min-w-0"><h3 className="truncate font-semibold">{beat.title}</h3><p className="truncate text-sm text-[#F4EBDD]/70">@{beat.sellerUsername || 'seller'} · {beat.genre || 'Beat'} · {beat.bpm || '--'} BPM · {beat.key || '--'}</p></div></div><audio className="mt-3 w-full" controls preload="none" src={beat.beatUrl} /></article>)}</div>}</section></main></div>;
}
