import { useState } from 'react';
import { ArrowLeft, LogOut, Moon, Sun, Trash2, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import StarlightLogo from '../components/StarlightLogo';

const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:4000';

export default function Settings({ user, onLogout }) {
  const navigate = useNavigate();
  const [theme, setTheme] = useState(() => localStorage.getItem('theme') || 'dark');
  const changeTheme = (value) => { setTheme(value); localStorage.setItem('theme', value); document.documentElement.classList.toggle('theme-light', value === 'light'); };
  const deactivateAccount = async () => { if (!window.confirm('Temporarily deactivate your account?')) return; const res = await fetch(apiUrl + '/api/auth/' + user.id + '/deactivate', { method: 'POST' }); if (res.ok) onLogout(); };
  const deleteAccount = async () => { if (!window.confirm('Permanently delete your account and all data? This cannot be undone.')) return; const res = await fetch(apiUrl + '/api/users/' + user.id, { method: 'DELETE' }); if (res.ok) onLogout(); };
  return <div className="min-h-screen bg-primary-background px-5 pb-20 text-primary-label sm:px-8"><header className="mx-auto flex max-w-2xl items-center justify-between py-4"><Link to="/library" className="grid h-10 w-10 place-items-center rounded-full bg-shading hover:bg-highlight" aria-label="Back"><ArrowLeft className="h-5 w-5" /></Link><h1 className="text-base font-bold tracking-tight text-[#F7F4EC]">Settings</h1><span className="w-10" /></header><main className="mx-auto max-w-2xl py-8"><h1 className="text-3xl font-semibold">Settings</h1><p className="mt-2 text-sm text-secondary-label">Manage your account and preferences.</p><section className="mt-8 divide-y divide-border overflow-hidden rounded-2xl border border-border bg-shading/30"><button onClick={() => navigate('/profile/' + user.id)} className="flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-highlight"><UserRound className="h-5 w-5" />Edit profile</button><div className="flex items-center justify-between px-5 py-4"><span className="flex items-center gap-3 text-sm font-semibold">{theme === 'dark' ? <Moon className="h-5 w-5" /> : <Sun className="h-5 w-5" />}Theme</span><div className="flex gap-2">{['dark', 'light'].map((mode) => <button key={mode} onClick={() => changeTheme(mode)} className={`rounded-full px-3 py-1.5 text-xs font-semibold capitalize ${theme === mode ? 'bg-primary-label text-primary-background' : 'bg-highlight'}`}>{mode}</button>)}</div></div><button onClick={onLogout} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-semibold hover:bg-highlight"><LogOut className="h-5 w-5" />Log out</button><button onClick={deactivateAccount} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-semibold text-amber-400 hover:bg-amber-500/10"><Trash2 className="h-5 w-5" />Temporarily deactivate account</button><button onClick={deleteAccount} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-semibold text-red-400 hover:bg-red-500/10"><Trash2 className="h-5 w-5" />Permanently delete account</button></section></main></div>;
}
