import { useState } from 'react';
import { ArrowLeft, LogOut, Trash2, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import StarlightLogo from '../components/StarlightLogo';
import ConfirmModal from '../components/ConfirmModal';

const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:4000';

export default function Settings({ user, onLogout }) {
  const navigate = useNavigate();
  const [action, setAction] = useState(null); const [feedback, setFeedback] = useState('');
  const confirmAction = async () => { const isDelete = action === 'delete'; const url = isDelete ? apiUrl + '/api/users/' + user.id : apiUrl + '/api/auth/' + user.id + '/deactivate'; try { const res = await fetch(url, { method: isDelete ? 'DELETE' : 'POST' }); if (!res.ok) throw new Error('Could not complete this request.'); setFeedback(isDelete ? 'Account deleted successfully.' : 'Account deactivated successfully.'); setAction(null); setTimeout(onLogout, 700); } catch (error) { setAction(null); setFeedback(error.message || 'Could not complete this request.'); } };
  return <div className="min-h-screen bg-primary-background text-primary-label px-5 pb-20 sm:px-8"><header className="mx-auto flex max-w-2xl items-center justify-between py-4"><Link to="/library" className="grid h-10 w-10 place-items-center rounded-full bg-shading hover:bg-highlight" aria-label="Back"><ArrowLeft className="h-5 w-5" /></Link><h1 className="font-display text-base font-bold tracking-wider text-primary-label">sEtTiNgS</h1><span className="w-10" /></header><main className="mx-auto max-w-2xl py-8"><h1 className="font-display text-3xl font-bold tracking-wider text-primary-label">sEtTiNgS</h1><p className="mt-2 text-sm text-secondary-label">Manage your account and preferences.</p>{feedback && <p role="status" className="mt-4 rounded-xl bg-shading px-4 py-3 text-sm">{feedback}</p>}<section className="mt-8 divide-y divide-border overflow-hidden rounded-2xl border border-border bg-shading/30"><button onClick={() => navigate('/profile/' + user.id)} className="flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-highlight"><UserRound className="h-5 w-5" />Edit profile</button><button onClick={onLogout} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-semibold hover:bg-highlight"><LogOut className="h-5 w-5" />Log out</button><button onClick={() => setAction('deactivate')} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-semibold text-amber-400 hover:bg-amber-500/10"><Trash2 className="h-5 w-5" />Temporarily deactivate account</button><button onClick={() => setAction('delete')} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-semibold text-red-400 hover:bg-red-500/10"><Trash2 className="h-5 w-5" />Permanently delete account</button></section></main><ConfirmModal isOpen={Boolean(action)} onClose={() => setAction(null)} onConfirm={confirmAction} title={action === 'delete' ? 'Delete account?' : 'Deactivate account?'} message={action === 'delete' ? 'This permanently removes your account and associated data.' : 'Your account will be temporarily deactivated until you return.'} confirmText={action === 'delete' ? 'Delete account' : 'Deactivate'} /></div>;
}
